repos:
  - repo: local
    hooks:
    - id: black
      stages: [commit]
      name: black
      entry: "python -m black ."
      language: system
      language_version: python3.7
      pass_filenames: false

  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.8.4
    hooks:
      - id: flake8
        language_version: python3.7
        additional_dependencies: [flake8-bugbear]

  - repo: https://github.com/timothycrosley/isort
    rev: 5.6.4
    hooks:
      - id: isort
        additional_dependencies: [toml]
        language_version: python3.7

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.3.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: debug-statements

  - repo: local
    hooks:
    - id: mypy
      stages: [commit]
      name: mypy
      entry: "python -m mypy src/panoramic"
      language: system
      pass_filenames: false
