SELECT comparison_enhanced_cpm_cc5f1f74b26a5c9c AS comparison_enhanced_cpm_cc5f1f74b26a5c9c, enhanced_cpm AS enhanced_cpm 
FROM (SELECT __comparison_enhanced_cpm2_f41b6627a5adb5cb / nullif(__comparison_enhanced_cpm3_d0fade8d857b01d0, 0) AS comparison_enhanced_cpm_cc5f1f74b26a5c9c, __enhanced_cpm2 / nullif(__enhanced_cpm3, 0) AS enhanced_cpm 
FROM (SELECT sum(1000 * CASE WHEN (__comparison_enhanced_cpm1_5e17ada29a9a7f08 = 'LINK_CLICKS') THEN (coalesce(comparison_facebook_ads_spend_ee3c8ce54c851643, 0) + coalesce(comparison_adwords_spend_6e7fc1618e83f21b, 0)) * 1.5 ELSE coalesce(comparison_facebook_ads_spend_ee3c8ce54c851643, 0) + coalesce(comparison_adwords_spend_6e7fc1618e83f21b, 0) END) AS __comparison_enhanced_cpm2_f41b6627a5adb5cb, sum(coalesce(comparison_facebook_ads_impressions_1425cd65e3336e0a, 0) + coalesce(comparison_adwords_impressions_e5de26c1212b86b4, 0)) AS __comparison_enhanced_cpm3_d0fade8d857b01d0, sum(1000 * CASE WHEN (__enhanced_cpm1 = 'LINK_CLICKS') THEN (coalesce(facebook_ads_spend_5811c78c7c741b5a, 0) + coalesce(adwords_spend_a4a9ec96df6a4664, 0)) * 1.5 ELSE coalesce(facebook_ads_spend_5811c78c7c741b5a, 0) + coalesce(adwords_spend_a4a9ec96df6a4664, 0) END) AS __enhanced_cpm2, sum(coalesce(facebook_ads_impressions_0bf2e36fb4e71190, 0) + coalesce(adwords_impressions_c62a8b11347285de, 0)) AS __enhanced_cpm3 
FROM (SELECT data_dataframe.__comparison_enhanced_cpm1_5e17ada29a9a7f08 AS __comparison_enhanced_cpm1_5e17ada29a9a7f08, data_dataframe.__enhanced_cpm1 AS __enhanced_cpm1, comparison_dataframe.comparison_generic_impressions_d3f32714bdd4789d AS comparison_generic_impressions_d3f32714bdd4789d, comparison_dataframe.comparison_generic_spend_fb5c2ccbf2a78f9e AS comparison_generic_spend_fb5c2ccbf2a78f9e, data_dataframe.generic_impressions AS generic_impressions, data_dataframe.generic_spend AS generic_spend, data_dataframe.objective AS objective 
FROM (SELECT objective AS __comparison_enhanced_cpm1_5e17ada29a9a7f08, objective AS __enhanced_cpm1, generic_impressions, generic_spend, objective 
FROM (SELECT generic_impressions, generic_spend, objective 
FROM (SELECT sum(coalesce(q0.generic_impressions,0)+coalesce(q1.generic_impressions,0)) as generic_impressions, sum(coalesce(q0.generic_spend,0)+coalesce(q1.generic_spend,0)) as generic_spend, coalesce(q0.objective, q1.objective) AS objective 
FROM (SELECT adwords_column_mock, __data_source 
FROM adwords_table_mock) AS q0 FULL OUTER JOIN (SELECT facebook_column_mock, __data_source 
FROM facebook_table_mock) AS q1 ON q0.__data_source = q1.__data_source GROUP BY coalesce(q0.objective, q1.objective)))) AS data_dataframe LEFT OUTER JOIN (SELECT generic_impressions AS comparison_generic_impressions_d3f32714bdd4789d, generic_spend AS comparison_generic_spend_fb5c2ccbf2a78f9e, objective AS objective 
FROM (SELECT generic_impressions, generic_spend, objective 
FROM (SELECT sum(coalesce(q0.generic_impressions,0)+coalesce(q1.generic_impressions,0)) as generic_impressions, sum(coalesce(q0.generic_spend,0)+coalesce(q1.generic_spend,0)) as generic_spend, coalesce(q0.objective, q1.objective) AS objective 
FROM (SELECT adwords_comparison_column_mock, __data_source 
FROM adwords_comparison_table_mock) AS q0 FULL OUTER JOIN (SELECT facebook_comparison_column_mock, __data_source 
FROM facebook_comparison_table_mock) AS q1 ON q0.__data_source = q1.__data_source GROUP BY coalesce(q0.objective, q1.objective)))) AS comparison_dataframe ON data_dataframe.objective = comparison_dataframe.objective OR (data_dataframe.objective IS NULL AND comparison_dataframe.objective IS NULL))))
 LIMIT 100